CityChainFoundation/city-hub

main.js
main.ts
src/app/components/account/create/create.component.html
src/app/components/account/create/create.component.scss
src/app/components/account/create/create.component.ts
src/app/components/load/load.component.html
src/app/components/load/load.component.ts
src/app/components/login/login.component.ts
src/app/components/root/root.component.ts
src/app/services/api.service.ts

- Add support for the new API ports.
- Support more coin networks and change icons.
- Improve error handling during login and loading.

Add support for recent City Chain (full node) changes

---

src/app/app-routing.module.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/dashboard/dashboard.module.ts
src/app/components/wallet/receive/receive.component.html
src/app/components/wallet/receive/receive.component.scss
src/app/components/wallet/receive/receive.component.ts
src/app/components/wallet/receive/receive.module.ts
src/app/components/wallet/send/send.component.html
src/app/components/wallet/send/send.component.ts
src/app/components/wallet/send/send.module.ts
src/app/components/wallet/wallet-routing.module.ts
src/app/components/wallet/wallet.module.ts
src/app/services/api.service.ts
src/app/shared/app-shared.module.ts
src/app/shared/pipes/coin-notation.pipe.ts

- Basic support for showing address as QR code and addresses in list.
- Dashboard updates with current wallet status and transaction history.
- Transaction details is missing.

Add support for receiving coins #11

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/dashboard/dashboard.component.ts
src/app/components/details/details.component.html
src/app/components/details/details.component.scss
src/app/components/details/details.component.ts
src/app/components/details/details.module.ts
src/app/components/root/root.component.html
src/app/components/root/root.component.scss
src/app/components/root/root.component.ts
src/app/components/root/root.module.ts
src/app/services/details.service.ts
src/app/services/services.module.ts

- Add a sidebar for transaction details.
- Due to issue with named route, the details pane was implemented with a controller and service. Look into refactoring in the future, when named routing and lazy-loading works better.

Add sidebar for transaction details #6

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/about/about.component.html
src/app/components/about/about.component.scss
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/dashboard/dashboard.component.ts
src/app/components/load/load.component.html
src/app/components/merchants/merchants.component.html
src/app/components/merchants/merchants.component.scss
src/app/components/merchants/merchants.component.ts
src/app/components/merchants/merchants.module.ts
src/app/components/root/root.component.html
src/app/components/wallet/wallet.component.html
src/app/components/wallet/wallet.component.scss
src/app/components/wallet/wallet.component.ts
src/app/components/wallet/wallet.module.ts
src/app/services/application-state.service.ts
src/app/services/services.module.ts
src/app/services/wallet.service.ts
src/styles/styles.scss

- Move staking and transaction history from dashboard to wallet.
- Migrate wallet logic into a WalletService.
- Fix some branding from City Chain to City Hub.

Add wallet features #5

---

src/app/components/account/create/create.component.html
src/app/components/account/create/create.component.ts
src/app/components/account/recover/recover.component.html
src/app/components/account/recover/recover.component.scss
src/app/components/account/recover/recover.component.ts
src/app/components/login/login.component.ts
src/app/components/logout/logout.component.ts
src/app/components/wallet/wallet.component.html
src/app/services/wallet.service.ts
src/styles/styles.scss

- Allows users to restore accounts.
- Validates user input, could perhaps do clientside validation of nmemonic by using bitcore-lib.

Add account restore to City Hub #19

---

.gitignore
README.md
appveyor.yml
main.js
main.ts
scripts/build-win-x64-package.ps1
scripts/build-win-x86-package.ps1

- Builds and embedd the daemon for City Chain, within City Hub.
- Adds appveyor script, needs testing to see if it works.

Complete build setup for packging electron app for deployment

---

electron-builder.json
main.js
main.ts
package-lock.json
package.json

- Made it work with some additional logging.
- Releases must be made non-pre-release to be seen by updater.

Fix for auto-update

---

main.js

- Need to figure out a proper way to do some additional debug logging of tasks that happens within the main electron thread. Need a proper location to the log files.

Remove additional debug logging

---

src/app/components/about/changes/changes.component.html
src/app/components/account/recover/recover.component.html
src/app/components/account/recover/recover.component.scss
src/app/components/load/load.component.ts
src/app/components/login/login.component.ts
src/app/components/network/network.component.html
src/app/components/root/root.component.html
src/app/components/root/root.component.ts
src/app/components/settings/settings.component.html
src/app/components/settings/settings.component.ts
src/app/components/wallet/send/send.component.ts
src/app/services/application-state.service.ts
src/app/services/theming.service.ts

- Update change log.
- Add prefix to all local storage settings.
- Add persistent menu expand/collapse, defaults to open.
- Add animation to account restore.
- Remove features not support yet.

Various minor improvements

---

DEVELOPMENT.md
README.md

- Clean up README.md to focus on users.

Move dev instructions to DEVELOPMENT.md

---

src/app/components/history/history.component.html
src/app/components/history/history.component.ts

- Should avoid skipping PR builds to avoid these issues.
- Fixes issues that only appear when building for production.

Fix build error

---

build.yml
main.js
main.ts
package.json
src/app/classes/transaction-building.ts
src/app/components/about/about.component.ts
src/app/components/about/changes/changes.component.html
src/app/components/dashboard/dashboard.component.ts
src/app/components/logout/logout.component.ts
src/app/components/merchants/merchants.component.ts
src/app/components/settings/settings.component.html
src/app/components/settings/settings.component.scss
src/app/components/settings/settings.component.ts
src/app/components/wallet/receive/receive.component.html
src/app/components/wallet/receive/receive.component.ts
src/app/components/wallet/send/send.component.ts
src/app/components/wallet/wallet.component.html
src/app/components/wallet/wallet.component.ts
src/app/services/api.service.ts
src/app/services/wallet.service.ts

- Add setting to have user pick their wallet mode.
- Make sure the receive address is always the first address.

Add support for single-address-mode #60

---

src/app/components/about/about.component.ts
src/app/components/dashboard/dashboard.component.ts
src/app/components/history/block/block.component.ts
src/app/components/history/transaction/transaction.component.ts
src/app/components/logout/logout.component.ts
src/app/components/merchants/merchants.component.ts

- Page mode was set incorrectly on many pages.
- Added the proper reset on ngOnDestroy for a couple of pages that was missing it.

Page mode was set incorrectly

---

build.yml
package.json
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/paperwallet/paperwallet.component.html
src/app/components/paperwallet/paperwallet.component.scss
src/app/components/paperwallet/paperwallet.component.ts
src/app/components/paperwallet/paperwallet.module.ts

- Link from the dashboard into the paperwallet.
- Currently loaded from webserver, should in the future embed the full code allowing users to go and generate it offline if they want to.

Add paperwallet to City Hub

---

src/app/components/account/recover/recover.component.ts

Set restored account as default on login page

---

src/app/services/api.service.ts

- Recently the API for staking was changed, fix City Hub with correct URLs.

Fix the breaking change in API URL for staking

---

package.json
src/app/components/root/root.component.html
src/app/components/root/root.component.ts
src/app/components/settings/settings.component.html
src/app/components/settings/settings.component.ts
src/app/components/wallet/wallet.component.html
src/app/components/wallet/wallet.component.ts
src/app/shared/app-modes.ts

- Default to BASIC mode for new users.
- Advanced can be set in Settings.
- Advanced is required for staking UI.
Closes: #67

Add BASIC and ADVANCED mode

---

main.js
src/app/components/about/licenses/licenses.component.ts
src/app/components/account/create/create.component.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/history/block/block.component.ts
src/app/components/history/history.component.ts
src/app/components/history/transaction/transaction.component.ts
src/app/components/login/login.component.ts
src/app/components/logout/logout.component.ts
src/app/components/wallet/receive/receive.component.ts
src/app/components/wallet/send/send.component.ts
src/app/components/wallet/wallet.component.html
src/app/services/api.service.ts
src/app/services/wallet.service.ts

- This has not been fully tested, but to fix runtime error it is pushed.
- Need more testing of all API methods.

Migrate from deprecated http module

---

src/app/components/update/update.component.html
src/app/components/update/update.module.ts
src/app/services/update.service.ts
src/app/shared/app-shared.module.ts
src/app/shared/directives/router-link-back.directive.ts
src/app/shared/pipes/size-unit.pipe.ts

remove function bytesToSize from update service and add it as a pipe
add a check on routingBackLink to send back to the History page when closing block history

Add sizeUnit pipe and change routerLinkBack function on History

---

package.json
src/app/components/about/changes/changes.component.html
src/app/components/account/create/create.component.ts
src/app/components/account/recover/recover.component.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/dashboard/dashboard.component.ts
src/app/components/dashboard/dashboard.module.ts
src/app/components/wallet/send/send.component.ts
src/app/components/wallet/wallet.component.html
src/app/components/wallet/wallet.component.scss
src/app/components/wallet/wallet.component.ts
src/app/services/wallet.service.ts

- Improve the dashboard layout.
- Fix a few minor issues after REST API changes on the City Chain daemon.

Improve dashboard layout

---

electron-builder.json
package.json
src/app/components/about/changes/changes.component.html
src/app/components/account/account-routing.module.ts
src/app/components/account/create/create.component.html
src/app/components/account/create/create.component.ts
src/app/components/account/recover/recover.component.html
src/app/components/dashboard/dashboard.component.html
src/app/components/wallet/wallet.component.html
src/app/shared/directives/password-validation.directive.ts

- Simplified the language.
- Improved the validation and steps.
- Hide the unconfirmed amount when zero.

Improve the sentences and validation on account create

---

main.js
main.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/load/load.component.ts
src/app/components/login/login.component.ts
src/app/services/api.service.ts
src/app/services/chain.service.ts

- Add Stratis and Stratis (Test) as options in the load.
- The developer (user) is responsible to launch the daemon manually to be able to use the Stratis mode, until next release.

Re-enable multi-chain selection on startup

---

build.yml
main.js
main.ts
src/app/components/advanced/advanced.component.html
src/app/components/advanced/advanced.component.scss
src/app/components/advanced/advanced.component.ts
src/app/components/load/load.component.ts
src/app/components/login/login.component.html

- Breaking changes in the City Chain daemon, require a database delete.
- Add Advance option to make it easy to wipe local database copy.

Add advanced option to delete blockchain database

---

.vscode/extensions.json
README.md
main.js
package-lock.json
package.json
src/app/components/dashboard/dashboard.component.html
src/app/components/wallet/wallet.component.html

- Memory leak with delay, upgrading to fix.
- Upgrades TypeScript, required for latest rxjs.
- Add the name of a wallet to the UI.
- Add list of suggested extensions.

Update the rxjs library

---

main.js
main.ts
package.json
src/app/components/account/create/create.component.ts
src/app/components/account/recover/recover.component.ts
src/app/components/history/block/block.component.ts
src/app/components/load/load.component.ts
src/app/components/login/login.component.ts
src/app/components/logout/logout.component.ts
src/app/components/wallet/send/send.component.ts
src/app/components/wallet/wallet.component.ts
src/app/services/api.service.ts
src/app/services/wallet.service.ts
src/styles/styles.scss

- Improves the error handling for API.
- Improves wallet feature, with auto-update of transaction history and balance.
- Fixed issue where balance would stop to update after error on initial login.
- Visually improve the error toast, making it more clear when errors happen.
- Closes #38
- Includes some work on the #5 issue.

Improve error handling

---

build.yml
package.json
src/app/components/about/changes/changes.component.html
src/app/components/history/block/block.component.html
src/app/components/history/block/block.component.ts
src/app/components/history/history.component.html
src/app/components/history/history.component.ts
src/app/components/logout/logout.component.html
src/app/components/logout/logout.component.ts
src/app/components/wallet/wallet.component.html
src/app/components/wallet/wallet.component.scss
src/app/components/wallet/wallet.component.ts
src/app/services/api.service.ts
src/app/services/chain.service.ts
src/app/services/wallet.service.ts
src/styles/themes/theming.scss

- Make sorting and filtering for transaction history.
- Make logout conditional, only show warning when user is staking.
- Update the initial date for account recovery.
- Improve navigation on the blockchain history.

Improve the wallet history

---

src/app/components/wallet/wallet.component.html
src/app/components/wallet/wallet.component.scss
src/app/components/wallet/wallet.component.ts

Add different style for unconfirmed transactions

---

build.yml
package.json
src/app/components/about/changes/changes.component.html
src/app/components/history/block/block.component.html
src/app/components/history/block/block.component.ts
src/app/components/history/history.component.html

- Fix a minor bug with block explorer and keyboard navigation.
- Upgrade to latest City Chain daemon, which has many bug fixes and improvements.

City Hub (Release 6)

---

package.json
src/app/classes/coincap-asset.ts
src/app/components/about/changes/changes.component.html
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/dashboard/dashboard.component.ts
src/app/services/coincap.service.ts
src/app/shared/app-shared.module.ts
src/app/shared/pipes/price-unit.pipe.ts

- Add the coin ticker on dashboard, use Bitcoin until Coincap supports City.
- Closes #111

Add coin ticker on dashboard

---

.github/workflows/build.yml
.github/workflows/pull-request.yml
package.json
src/app/components/about/changes/changes.component.html

- Version 22 of City Chain includes an important bug fix for network connectivity.

Update build to use latest City Chain

---

.vscode/extensions.json
package.json
src/app/components/about/changes/changes.component.html
src/app/components/login/login.component.html
src/app/components/root/root.component.html
src/app/components/root/root.component.scss
src/app/components/root/root.component.ts
src/app/components/settings/settings.component.html

- Fix the missing icon on menu header.

Improve the menu header layout
